export const EMOJI_CATEGORIES = [
  { id: 'emo_smileys', label: '😀 Smileys & Emotion', group: 'Emojis', icon: '😀' , symbols: ["😀","😂","😍","😎","😢","😡","🥳","🤔","😴","🤮","🤯","🥰","😇","🤪","🤫","🤭","🤗","🤩","🤠","🤡"] },
  { id: 'emo_people', label: '🙋 People & Body', group: 'Emojis', icon: '🙋' , symbols: ["🙋","🤷","🤦","🏃","💃","🕺","🛀","🛌","👨‍🚀","👩‍⚖️","👨‍🎨","🦸‍♀️","🧛‍♂️","🧜‍♀️","🧚‍♂️","🧟‍♀️","🧞‍♂️","🧝‍♀️","🤱","👼"] },
  { id: 'emo_animals', label: '🐶 Animals & Nature', group: 'Emojis', icon: '🐶' , symbols: ["🐶","🐱","🐭","🐹","🐰","🦊","🐻","🐼","🐨","🐯","🦁","🐮","🐷","🐸","🐒","🐔","🐧","🐦","🐤","🐺"] },
  { id: 'emo_food', label: '🍔 Food & Drink', group: 'Emojis', icon: '🍔' , symbols: ["🍔","🍕","🌭","🌮","🌯","🥙","🍗","🍖","🥩","🍟","🍔","🍟","🌭","🍿","🧂","🥓","🥚","🍳","🧇","🥞"] },
  { id: 'emo_activities', label: '⚽ Activities & Sports', group: 'Emojis', icon: '⚽' , symbols: ["⚽","🏀","🏈","⚾","🥎","🎾","🏐","🏉","🎱","🪀","🏓","🏸","🏒","🏑","🥍","🏏","🪃","🥅","⛳","🪁"] },
  { id: 'emo_travel', label: '🚗 Travel & Places', group: 'Emojis', icon: '🚗' , symbols: ["🚗","🚕","🚙","🚌","🚎","🏎️","🚓","🚑","🚒","🚐","🛻","🚚","🚛","🚜","🦯","🦽","🦼","🛴","🚲","🛵"] },
  { id: 'emo_objects', label: '💡 Objects', group: 'Emojis', icon: '💡' , symbols: ["💡","🔦","🏮","📔","📕","📖","📗","📘","📙","📚","📓","📒","📃","📜","📄","📰","🗞️","📑","🔖","🏷️"] },
  { id: 'emo_symbols', label: '🔣 Symbols', group: 'Emojis', icon: '🔣' , symbols: ["🔣","🔤","🔡","🔠","🆖","🆗","🆙","🆒","🆕","🆓","0️⃣","1️⃣","2️⃣","3️⃣","4️⃣","5️⃣","6️⃣","7️⃣","8️⃣","9️⃣"] },
  { id: 'emo_flags', label: '🏳️ Flags', group: 'Emojis', icon: '🏳️' , symbols: ["🏳️","🏴","🏁","🚩","🏳️‍🌈","🏳️‍⚧️","🏴‍☠️","🇦🇫","🇦🇽","🇦🇱","🇩🇿","🇦🇸","🇦🇩","🇦🇴","🇦🇮","🇦🇶","🇦🇬","🇦🇷","🇦🇲","🇦🇼"] },
  { id: 'emo_hearts', label: '❤️ Hearts', group: 'Emojis', icon: '❤️' , symbols: ["❤️","🧡","💛","💚","💙","💜","🖤","🤍","🤎","💔","❤️‍🔥","❤️‍🩹","❣️","💕","💞","💓","💗","💖","💘","💝"] },
  { id: 'emo_stars', label: '⭐ Stars', group: 'Emojis', icon: '⭐' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_moon', label: '🌙 Moon & Space', group: 'Emojis', icon: '🌙' , symbols: ["🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉"] },
  { id: 'emo_weather', label: '☀️ Weather', group: 'Emojis', icon: '☀️' , symbols: ["☀️","🌤️","⛅","🌥️","☁️","🌦️","🌧️","⛈️","🌩️","🌨️","❄️","☃️","⛄","🌬️","💨","🌪️","🌫️","🌈","☔","💧"] },
  { id: 'emo_plants', label: '🌿 Plants & Flowers', group: 'Emojis', icon: '🌿' , symbols: ["🌿","🌱","🌲","🌳","🌴","🌵","🌾","🌿","☘️","🍀","🍁","🍂","🍃","🍄","🌰","🌺","🌻","🌼","🌷","🌹"] },
  { id: 'emo_fruits', label: '🍎 Fruits & Vegetables', group: 'Emojis', icon: '🍎' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_sea', label: '🐟 Sea Life', group: 'Emojis', icon: '🐟' , symbols: ["🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨"] },
  { id: 'emo_dino', label: '🦖 Dinosaurs & Prehistoric', group: 'Emojis', icon: '🦖' , symbols: ["✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥"] },
  { id: 'emo_fantasy', label: '🐉 Fantasy Creatures', group: 'Emojis', icon: '🐉' , symbols: ["🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀"] },
  { id: 'emo_magic', label: '👑 Fantasy & Magic', group: 'Emojis', icon: '👑' , symbols: ["🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍"] },
  { id: 'emo_faces', label: '🎭 Faces & Costumes', group: 'Emojis', icon: '🎭' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_clothing', label: '👕 Clothing & Accessories', group: 'Emojis', icon: '👕' , symbols: ["⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠"] },
  { id: 'emo_jewelry', label: '💍 Jewelry', group: 'Emojis', icon: '💍' , symbols: ["🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀"] },
  { id: 'emo_buildings', label: '🏠 Buildings & Architecture', group: 'Emojis', icon: '🏠' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_geography', label: '🌍 Geography & Maps', group: 'Emojis', icon: '🌍' , symbols: ["🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀"] },
  { id: 'emo_space', label: '🚀 Space & Astronomy', group: 'Emojis', icon: '🚀' , symbols: ["🚀","🛸","🛰️","🪐","☄️","🌠","🌌","🌑","🌒","🌓","🌔","🌕","🌖","🌗","🌘","🌙","🌚","🌛","🌜","☀️"] },
  { id: 'emo_time', label: '⏰ Time & Calendar', group: 'Emojis', icon: '⏰' , symbols: ["🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀"] },
  { id: 'emo_education', label: '📚 Education', group: 'Emojis', icon: '📚' , symbols: ["🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉"] },
  { id: 'emo_business', label: '💼 Business & Office', group: 'Emojis', icon: '💼' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_technology', label: '💻 Technology', group: 'Emojis', icon: '💻' , symbols: ["🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀"] },
  { id: 'emo_devices', label: '📱 Devices', group: 'Emojis', icon: '📱' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_electronics', label: '🔋 Electronics', group: 'Emojis', icon: '🔋' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_tools', label: '🔧 Tools', group: 'Emojis', icon: '🔧' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_settings', label: '⚙️ Settings & UI', group: 'Emojis', icon: '⚙️' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_science', label: '🧪 Science', group: 'Emojis', icon: '🧪' , symbols: ["🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀"] },
  { id: 'emo_medical', label: '⚕️ Medical & Healthcare', group: 'Emojis', icon: '⚕️' , symbols: ["💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️"] },
  { id: 'emo_music', label: '🎵 Music', group: 'Emojis', icon: '🎵' , symbols: ["🎵","🎶","🎼","🎤","🎧","🎷","🎸","🎹","🎺","🎻","🪕","🥁","🪘","📻","📺","📼","📹","🎥","📽️","🎬"] },
  { id: 'emo_movies', label: '🎬 Movies & Entertainment', group: 'Emojis', icon: '🎬' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_art', label: '🎨 Art & Design', group: 'Emojis', icon: '🎨' , symbols: ["🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚"] },
  { id: 'emo_photo', label: '📸 Photography', group: 'Emojis', icon: '📸' , symbols: ["✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥"] },
  { id: 'emo_books', label: '📖 Books & Literature', group: 'Emojis', icon: '📖' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_shopping', label: '🛒 Shopping', group: 'Emojis', icon: '🛒' , symbols: ["⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠"] },
  { id: 'emo_money', label: '💰 Money & Finance', group: 'Emojis', icon: '💰' , symbols: ["🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀"] },
  { id: 'emo_charts', label: '📈 Charts & Statistics', group: 'Emojis', icon: '📈' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_packages', label: '📦 Packages & Shipping', group: 'Emojis', icon: '📦' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_mail', label: '✉️ Mail & Communication', group: 'Emojis', icon: '✉️' , symbols: ["💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️"] },
  { id: 'emo_internet', label: '🌐 Internet & Social Media', group: 'Emojis', icon: '🌐' , symbols: ["🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚"] },
  { id: 'emo_gaming', label: '🎮 Gaming', group: 'Emojis', icon: '🎮' , symbols: ["⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠"] },
  { id: 'emo_chess', label: '♟️ Chess', group: 'Emojis', icon: '♟️' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_board', label: '🎲 Board Games', group: 'Emojis', icon: '🎲' , symbols: ["🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎"] },
  { id: 'emo_cards', label: '🃏 Playing Cards', group: 'Emojis', icon: '🃏' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_casino', label: '🎰 Casino', group: 'Emojis', icon: '🎰' , symbols: ["✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥"] },
  { id: 'emo_awards', label: '🏆 Awards & Achievements', group: 'Emojis', icon: '🏆' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_culture', label: '🏛️ Culture', group: 'Emojis', icon: '🏛️' , symbols: ["🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀"] },
  { id: 'emo_religion', label: '🕊️ Religion & Spirituality', group: 'Emojis', icon: '🕊️' , symbols: ["🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉"] },
  { id: 'emo_holidays', label: '🎉 Holidays & Celebrations', group: 'Emojis', icon: '🎉' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_warnings', label: '⚠️ Warnings & Safety', group: 'Emojis', icon: '⚠️' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_emergency', label: '🚨 Emergency', group: 'Emojis', icon: '🚨' , symbols: ["🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀"] },
  { id: 'emo_recycling', label: '♻️ Recycling & Environment', group: 'Emojis', icon: '♻️' , symbols: ["⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠"] },
  { id: 'emo_pride', label: '🏳️‍🌈 Identity & Pride', group: 'Emojis', icon: '🏳️‍🌈' , symbols: ["🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀"] },
  { id: 'emo_regional_flags', label: '🏴 Regional Flags', group: 'Emojis', icon: '🏴' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_family', label: '👨‍👩‍👧 Family', group: 'Emojis', icon: '👨‍👩‍👧' , symbols: ["🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀"] },
  { id: 'emo_hand', label: '🤝 Hand Gestures', group: 'Emojis', icon: '🤝' , symbols: ["🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎"] },
  { id: 'emo_body', label: '👁️ Body Parts', group: 'Emojis', icon: '👁️' , symbols: ["🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀"] },
  { id: 'emo_professions', label: '🧑 Professions', group: 'Emojis', icon: '🧑' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_age', label: '👶 Age Groups', group: 'Emojis', icon: '👶' , symbols: ["🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀"] },
  { id: 'emo_pets', label: '🐾 Pets', group: 'Emojis', icon: '🐾' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_forest', label: '🌳 Forest & Nature', group: 'Emojis', icon: '🌳' , symbols: ["🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚"] },
  { id: 'emo_water', label: '🌊 Water & Ocean', group: 'Emojis', icon: '🌊' , symbols: ["🎮","📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻"] },
  { id: 'emo_fire', label: '🔥 Fire & Elements', group: 'Emojis', icon: '🔥' , symbols: ["🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀"] },
  { id: 'emo_gems', label: '💎 Gems & Minerals', group: 'Emojis', icon: '💎' , symbols: ["📚","🎨","🏆","🌍","🍎","🏀","🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮"] },
  { id: 'emo_currency', label: '🪙 Currency & Money', group: 'Emojis', icon: '🪙' , symbols: ["🚗","🏠","⚽","❤️","⭐","🌙","⚙️","💰","🎉","🔥","✨","💎","💻","🎮","📚","🎨","🏆","🌍","🍎","🏀"] },
];
