export const EMOJI_CATEGORIES = [
  {
    id: 'emo_smileys',
    label: '😀 Smileys & Emotions',
    group: 'Emojis',
    icon: '😀',
    symbols: [
      { char: '😀', code: '0x1f600', name: 'GRINNING FACE' },
      { char: '😁', code: '0x1f601', name: 'GRINNING FACE WITH SMILING EYES' },
      { char: '😂', code: '0x1f602', name: 'FACE WITH TEARS OF JOY' },
      { char: '😃', code: '0x1f603', name: 'SMILING FACE WITH OPEN MOUTH' },
      { char: '😄', code: '0x1f604', name: 'SMILING FACE WITH OPEN MOUTH AND SMILING EYES' },
      { char: '😅', code: '0x1f605', name: 'SMILING FACE WITH OPEN MOUTH AND COLD SWEAT' },
      { char: '😆', code: '0x1f606', name: 'SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES' },
      { char: '😇', code: '0x1f607', name: 'SMILING FACE WITH HALO' },
      { char: '😈', code: '0x1f608', name: 'SMILING FACE WITH HORNS' },
      { char: '😉', code: '0x1f609', name: 'WINKING FACE' },
      { char: '😊', code: '0x1f60a', name: 'SMILING FACE WITH SMILING EYES' },
      { char: '😋', code: '0x1f60b', name: 'FACE SAVOURING DELICIOUS FOOD' },
      { char: '😌', code: '0x1f60c', name: 'RELIEVED FACE' },
      { char: '😍', code: '0x1f60d', name: 'SMILING FACE WITH HEART-SHAPED EYES' },
      { char: '😎', code: '0x1f60e', name: 'SMILING FACE WITH SUNGLASSES' },
      { char: '😏', code: '0x1f60f', name: 'SMIRKING FACE' },
      { char: '😐', code: '0x1f610', name: 'NEUTRAL FACE' },
      { char: '😑', code: '0x1f611', name: 'EXPRESSIONLESS FACE' },
      { char: '😒', code: '0x1f612', name: 'UNAMUSED FACE' },
      { char: '😓', code: '0x1f613', name: 'FACE WITH COLD SWEAT' },
      { char: '😔', code: '0x1f614', name: 'PENSIVE FACE' },
      { char: '😕', code: '0x1f615', name: 'CONFUSED FACE' },
      { char: '😖', code: '0x1f616', name: 'CONFOUNDED FACE' },
      { char: '😗', code: '0x1f617', name: 'KISSING FACE' },
      { char: '😘', code: '0x1f618', name: 'FACE THROWING A KISS' },
      { char: '😙', code: '0x1f619', name: 'KISSING FACE WITH SMILING EYES' },
      { char: '😚', code: '0x1f61a', name: 'KISSING FACE WITH CLOSED EYES' },
      { char: '😛', code: '0x1f61b', name: 'FACE WITH STUCK-OUT TONGUE' },
      { char: '😜', code: '0x1f61c', name: 'FACE WITH STUCK-OUT TONGUE AND WINKING EYE' },
      { char: '😝', code: '0x1f61d', name: 'FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES' },
      { char: '😞', code: '0x1f61e', name: 'DISAPPOINTED FACE' },
      { char: '😟', code: '0x1f61f', name: 'WORRIED FACE' },
      { char: '😠', code: '0x1f620', name: 'ANGRY FACE' },
      { char: '😡', code: '0x1f621', name: 'POUTING FACE' },
      { char: '😢', code: '0x1f622', name: 'CRYING FACE' },
      { char: '😣', code: '0x1f623', name: 'PERSEVERING FACE' },
      { char: '😤', code: '0x1f624', name: 'FACE WITH LOOK OF TRIUMPH' },
      { char: '😥', code: '0x1f625', name: 'DISAPPOINTED BUT RELIEVED FACE' },
      { char: '😦', code: '0x1f626', name: 'FROWNING FACE WITH OPEN MOUTH' },
      { char: '😧', code: '0x1f627', name: 'ANGUISHED FACE' },
      { char: '😨', code: '0x1f628', name: 'FEARFUL FACE' },
      { char: '😩', code: '0x1f629', name: 'WEARY FACE' },
      { char: '😪', code: '0x1f62a', name: 'SLEEPY FACE' },
      { char: '😫', code: '0x1f62b', name: 'TIRED FACE' },
      { char: '😬', code: '0x1f62c', name: 'GRIMACING FACE' },
      { char: '😭', code: '0x1f62d', name: 'LOUDLY CRYING FACE' },
      { char: '😮', code: '0x1f62e', name: 'FACE WITH OPEN MOUTH' },
      { char: '😯', code: '0x1f62f', name: 'HUSHED FACE' },
      { char: '😰', code: '0x1f630', name: 'FACE WITH OPEN MOUTH AND COLD SWEAT' },
      { char: '😱', code: '0x1f631', name: 'FACE SCREAMING IN FEAR' },
      { char: '😲', code: '0x1f632', name: 'ASTONISHED FACE' },
      { char: '😳', code: '0x1f633', name: 'FLUSHED FACE' },
      { char: '😴', code: '0x1f634', name: 'SLEEPING FACE' },
      { char: '😵', code: '0x1f635', name: 'DIZZY FACE' },
      { char: '😶', code: '0x1f636', name: 'FACE WITHOUT MOUTH' },
      { char: '😷', code: '0x1f637', name: 'FACE WITH MEDICAL MASK' },
      { char: '😸', code: '0x1f638', name: 'GRINNING CAT FACE WITH SMILING EYES' },
      { char: '😹', code: '0x1f639', name: 'CAT FACE WITH TEARS OF JOY' },
      { char: '😺', code: '0x1f63a', name: 'SMILING CAT FACE WITH OPEN MOUTH' },
      { char: '😻', code: '0x1f63b', name: 'SMILING CAT FACE WITH HEART-SHAPED EYES' },
      { char: '😼', code: '0x1f63c', name: 'CAT FACE WITH WRY SMILE' },
      { char: '😽', code: '0x1f63d', name: 'KISSING CAT FACE WITH CLOSED EYES' },
      { char: '😾', code: '0x1f63e', name: 'POUTING CAT FACE' },
      { char: '😿', code: '0x1f63f', name: 'CRYING CAT FACE' },
      { char: '🙀', code: '0x1f640', name: 'WEARY CAT FACE' },
      { char: '🙁', code: '0x1f641', name: 'SLIGHTLY FROWNING FACE' },
      { char: '🙂', code: '0x1f642', name: 'SLIGHTLY SMILING FACE' },
      { char: '🙃', code: '0x1f643', name: 'UPSIDE-DOWN FACE' },
      { char: '🙄', code: '0x1f644', name: 'FACE WITH ROLLING EYES' },
      { char: '🙅', code: '0x1f645', name: 'FACE WITH NO GOOD GESTURE' },
      { char: '🙆', code: '0x1f646', name: 'FACE WITH OK GESTURE' },
      { char: '🙋', code: '0x1f64b', name: 'HAPPY PERSON RAISING ONE HAND' },
      { char: '🙌', code: '0x1f64c', name: 'PERSON RAISING BOTH HANDS IN CELEBRATION' },
      { char: '🙎', code: '0x1f64e', name: 'PERSON WITH POUTING FACE' },
      { char: '🙏', code: '0x1f64f', name: 'PERSON WITH FOLDED HANDS' },
    ],
    isCustom: true,
  },
  {
    id: 'emo_symbols',
    label: '🔣 Symbols',
    group: 'Emojis',
    icon: '🔣',
    symbols: [
      { char: '☀', code: '0x2600', name: 'BLACK SUN WITH RAYS' },
      { char: '★', code: '0x2605', name: 'BLACK STAR' },
      { char: '☆', code: '0x2606', name: 'WHITE STAR' },
      { char: '☉', code: '0x2609', name: 'SUN' },
      { char: '☙', code: '0x2619', name: 'REVERSED ROTATED FLORAL HEART BULLET' },
      { char: '☡', code: '0x2621', name: 'CAUTION SIGN' },
      { char: '☢', code: '0x2622', name: 'RADIOACTIVE SIGN' },
      { char: '☣', code: '0x2623', name: 'BIOHAZARD SIGN' },
      { char: '☪', code: '0x262a', name: 'STAR AND CRESCENT' },
      { char: '☫', code: '0x262b', name: 'FARSI SYMBOL' },
      { char: '☮', code: '0x262e', name: 'PEACE SYMBOL' },
      { char: '☹', code: '0x2639', name: 'WHITE FROWNING FACE' },
      { char: '☺', code: '0x263a', name: 'WHITE SMILING FACE' },
      { char: '☻', code: '0x263b', name: 'BLACK SMILING FACE' },
      { char: '☼', code: '0x263c', name: 'WHITE SUN WITH RAYS' },
      { char: '☽', code: '0x263d', name: 'FIRST QUARTER MOON' },
      { char: '☾', code: '0x263e', name: 'LAST QUARTER MOON' },
      { char: '♀', code: '0x2640', name: 'FEMALE SIGN' },
      { char: '♂', code: '0x2642', name: 'MALE SIGN' },
      { char: '♡', code: '0x2661', name: 'WHITE HEART SUIT' },
      { char: '♥', code: '0x2665', name: 'BLACK HEART SUIT' },
      { char: '♭', code: '0x266d', name: 'MUSIC FLAT SIGN' },
      { char: '♮', code: '0x266e', name: 'MUSIC NATURAL SIGN' },
      { char: '♯', code: '0x266f', name: 'MUSIC SHARP SIGN' },
      { char: '♲', code: '0x2672', name: 'UNIVERSAL RECYCLING SYMBOL' },
      { char: '♻', code: '0x267b', name: 'BLACK UNIVERSAL RECYCLING SYMBOL' },
      { char: '♿', code: '0x267f', name: 'WHEELCHAIR SYMBOL' },
      { char: '⚀', code: '0x2680', name: 'DIE FACE-1' },
      { char: '⚁', code: '0x2681', name: 'DIE FACE-2' },
      { char: '⚂', code: '0x2682', name: 'DIE FACE-3' },
      { char: '⚃', code: '0x2683', name: 'DIE FACE-4' },
      { char: '⚄', code: '0x2684', name: 'DIE FACE-5' },
      { char: '⚅', code: '0x2685', name: 'DIE FACE-6' },
      { char: '⚐', code: '0x2690', name: 'WHITE FLAG' },
      { char: '⚑', code: '0x2691', name: 'BLACK FLAG' },
      { char: '⚛', code: '0x269b', name: 'ATOM SYMBOL' },
      { char: '⚠', code: '0x26a0', name: 'WARNING SIGN' },
      { char: '⚡', code: '0x26a1', name: 'HIGH VOLTAGE SIGN' },
      { char: '✅', code: '0x2705', name: 'WHITE HEAVY CHECK MARK' },
      { char: '✋', code: '0x270b', name: 'RAISED HAND' },
      { char: '✌', code: '0x270c', name: 'VICTORY HAND' },
      { char: '✍', code: '0x270d', name: 'WRITING HAND' },
      { char: '✓', code: '0x2713', name: 'CHECK MARK' },
      { char: '✔', code: '0x2714', name: 'HEAVY CHECK MARK' },
      { char: '✡', code: '0x2721', name: 'STAR OF DAVID' },
      { char: '✦', code: '0x2726', name: 'BLACK FOUR POINTED STAR' },
      { char: '✧', code: '0x2727', name: 'WHITE FOUR POINTED STAR' },
      { char: '✩', code: '0x2729', name: 'STRESS OUTLINED WHITE STAR' },
      { char: '✪', code: '0x272a', name: 'CIRCLED WHITE STAR' },
      { char: '✫', code: '0x272b', name: 'OPEN CENTRE BLACK STAR' },
      { char: '✬', code: '0x272c', name: 'BLACK CENTRE WHITE STAR' },
      { char: '✭', code: '0x272d', name: 'OUTLINED BLACK STAR' },
      { char: '✮', code: '0x272e', name: 'HEAVY OUTLINED BLACK STAR' },
      { char: '✯', code: '0x272f', name: 'PINWHEEL STAR' },
      { char: '✰', code: '0x2730', name: 'SHADOWED WHITE STAR' },
      { char: '✴', code: '0x2734', name: 'EIGHT POINTED BLACK STAR' },
      { char: '✵', code: '0x2735', name: 'EIGHT POINTED PINWHEEL STAR' },
      { char: '✶', code: '0x2736', name: 'SIX POINTED BLACK STAR' },
      { char: '❌', code: '0x274c', name: 'CROSS MARK' },
      { char: '❎', code: '0x274e', name: 'NEGATIVE SQUARED CROSS MARK' },
      { char: '❓', code: '0x2753', name: 'BLACK QUESTION MARK ORNAMENT' },
      { char: '❔', code: '0x2754', name: 'WHITE QUESTION MARK ORNAMENT' },
      { char: '❕', code: '0x2755', name: 'WHITE EXCLAMATION MARK ORNAMENT' },
      { char: '❗', code: '0x2757', name: 'HEAVY EXCLAMATION MARK SYMBOL' },
      { char: '❤', code: '0x2764', name: 'HEAVY BLACK HEART' },
      { char: '❥', code: '0x2765', name: 'ROTATED HEAVY BLACK HEART BULLET' },
      { char: '❦', code: '0x2766', name: 'FLORAL HEART' },
      { char: '❧', code: '0x2767', name: 'ROTATED FLORAL HEART BULLET' },
      { char: '➕', code: '0x2795', name: 'HEAVY PLUS SIGN' },
      { char: '➖', code: '0x2796', name: 'HEAVY MINUS SIGN' },
      { char: '➗', code: '0x2797', name: 'HEAVY DIVISION SIGN' },
      { char: '⭐', code: '0x2b50', name: 'WHITE MEDIUM STAR' },
    ],
    isCustom: true,
  },
  {
    id: 'emo_objects',
    label: '💡 Objects',
    group: 'Emojis',
    icon: '💡',
    symbols: [
      { char: '🌃', code: '0x1f303', name: 'NIGHT WITH STARS' },
      { char: '🌄', code: '0x1f304', name: 'SUNRISE OVER MOUNTAINS' },
      { char: '🌅', code: '0x1f305', name: 'SUNRISE' },
      { char: '🌇', code: '0x1f307', name: 'SUNSET OVER BUILDINGS' },
      { char: '🌑', code: '0x1f311', name: 'NEW MOON SYMBOL' },
      { char: '🌒', code: '0x1f312', name: 'WAXING CRESCENT MOON SYMBOL' },
      { char: '🌓', code: '0x1f313', name: 'FIRST QUARTER MOON SYMBOL' },
      { char: '🌔', code: '0x1f314', name: 'WAXING GIBBOUS MOON SYMBOL' },
      { char: '🌕', code: '0x1f315', name: 'FULL MOON SYMBOL' },
      { char: '🌖', code: '0x1f316', name: 'WANING GIBBOUS MOON SYMBOL' },
      { char: '🌗', code: '0x1f317', name: 'LAST QUARTER MOON SYMBOL' },
      { char: '🌘', code: '0x1f318', name: 'WANING CRESCENT MOON SYMBOL' },
      { char: '🌙', code: '0x1f319', name: 'CRESCENT MOON' },
      { char: '🌚', code: '0x1f31a', name: 'NEW MOON WITH FACE' },
      { char: '🌛', code: '0x1f31b', name: 'FIRST QUARTER MOON WITH FACE' },
      { char: '🌜', code: '0x1f31c', name: 'LAST QUARTER MOON WITH FACE' },
      { char: '🌝', code: '0x1f31d', name: 'FULL MOON WITH FACE' },
      { char: '🌞', code: '0x1f31e', name: 'SUN WITH FACE' },
      { char: '🌟', code: '0x1f31f', name: 'GLOWING STAR' },
      { char: '🌠', code: '0x1f320', name: 'SHOOTING STAR' },
      { char: '🌲', code: '0x1f332', name: 'EVERGREEN TREE' },
      { char: '🌳', code: '0x1f333', name: 'DECIDUOUS TREE' },
      { char: '🌴', code: '0x1f334', name: 'PALM TREE' },
      { char: '🌻', code: '0x1f33b', name: 'SUNFLOWER' },
      { char: '🎄', code: '0x1f384', name: 'CHRISTMAS TREE' },
      { char: '🎋', code: '0x1f38b', name: 'TANABATA TREE' },
      { char: '🎌', code: '0x1f38c', name: 'CROSSED FLAGS' },
      { char: '🏁', code: '0x1f3c1', name: 'CHEQUERED FLAG' },
      { char: '🏅', code: '0x1f3c5', name: 'SPORTS MEDAL' },
      { char: '🏳', code: '0x1f3f3', name: 'WAVING WHITE FLAG' },
      { char: '🏴', code: '0x1f3f4', name: 'WAVING BLACK FLAG' },
      { char: '💋', code: '0x1f48b', name: 'KISS MARK' },
      { char: '💓', code: '0x1f493', name: 'BEATING HEART' },
      { char: '💔', code: '0x1f494', name: 'BROKEN HEART' },
      { char: '💕', code: '0x1f495', name: 'TWO HEARTS' },
      { char: '💖', code: '0x1f496', name: 'SPARKLING HEART' },
      { char: '💗', code: '0x1f497', name: 'GROWING HEART' },
      { char: '💘', code: '0x1f498', name: 'HEART WITH ARROW' },
      { char: '💙', code: '0x1f499', name: 'BLUE HEART' },
      { char: '💚', code: '0x1f49a', name: 'GREEN HEART' },
      { char: '💛', code: '0x1f49b', name: 'YELLOW HEART' },
      { char: '💜', code: '0x1f49c', name: 'PURPLE HEART' },
      { char: '💢', code: '0x1f4a2', name: 'ANGER SYMBOL' },
      { char: '💤', code: '0x1f4a4', name: 'SLEEPING SYMBOL' },
      { char: '💥', code: '0x1f4a5', name: 'COLLISION SYMBOL' },
      { char: '💦', code: '0x1f4a6', name: 'SPLASHING SWEAT SYMBOL' },
      { char: '💨', code: '0x1f4a8', name: 'DASH SYMBOL' },
      { char: '💫', code: '0x1f4ab', name: 'DIZZY SYMBOL' },
      { char: '💯', code: '0x1f4af', name: 'HUNDRED POINTS SYMBOL' },
      { char: '💲', code: '0x1f4b2', name: 'HEAVY DOLLAR SIGN' },
      { char: '💴', code: '0x1f4b4', name: 'BANKNOTE WITH YEN SIGN' },
      { char: '💵', code: '0x1f4b5', name: 'BANKNOTE WITH DOLLAR SIGN' },
      { char: '💶', code: '0x1f4b6', name: 'BANKNOTE WITH EURO SIGN' },
      { char: '💷', code: '0x1f4b7', name: 'BANKNOTE WITH POUND SIGN' },
      { char: '💹', code: '0x1f4b9', name: 'CHART WITH UPWARDS TREND AND YEN SIGN' },
      { char: '📑', code: '0x1f4d1', name: 'BOOKMARK TABS' },
      { char: '📧', code: '0x1f4e7', name: 'E-MAIL SYMBOL' },
      { char: '📪', code: '0x1f4ea', name: 'CLOSED MAILBOX WITH LOWERED FLAG' },
      { char: '📫', code: '0x1f4eb', name: 'CLOSED MAILBOX WITH RAISED FLAG' },
      { char: '📬', code: '0x1f4ec', name: 'OPEN MAILBOX WITH RAISED FLAG' },
      { char: '📭', code: '0x1f4ed', name: 'OPEN MAILBOX WITH LOWERED FLAG' },
      { char: '🔖', code: '0x1f516', name: 'BOOKMARK' },
      { char: '🔗', code: '0x1f517', name: 'LINK SYMBOL' },
      { char: '🔠', code: '0x1f520', name: 'INPUT SYMBOL FOR LATIN CAPITAL LETTERS' },
      { char: '🔡', code: '0x1f521', name: 'INPUT SYMBOL FOR LATIN SMALL LETTERS' },
      { char: '🔢', code: '0x1f522', name: 'INPUT SYMBOL FOR NUMBERS' },
      { char: '🔣', code: '0x1f523', name: 'INPUT SYMBOL FOR SYMBOLS' },
      { char: '🔤', code: '0x1f524', name: 'INPUT SYMBOL FOR LATIN LETTERS' },
      { char: '🔯', code: '0x1f52f', name: 'SIX POINTED STAR WITH MIDDLE DOT' },
      { char: '🖤', code: '0x1f5a4', name: 'BLACK HEART' },
      { char: '🗸', code: '0x1f5f8', name: 'LIGHT CHECK MARK' },
    ],
    isCustom: true,
  },
  {
    id: 'emo_people',
    label: '🙋 People & Body',
    group: 'Emojis',
    icon: '🙋',
    symbols: [
      { char: '🤍', code: '0x1f90d', name: 'WHITE HEART' },
      { char: '🤎', code: '0x1f90e', name: 'BROWN HEART' },
      { char: '🤏', code: '0x1f90f', name: 'PINCHING HAND' },
      { char: '🤐', code: '0x1f910', name: 'ZIPPER-MOUTH FACE' },
      { char: '🤑', code: '0x1f911', name: 'MONEY-MOUTH FACE' },
      { char: '🤒', code: '0x1f912', name: 'FACE WITH THERMOMETER' },
      { char: '🤓', code: '0x1f913', name: 'NERD FACE' },
      { char: '🤔', code: '0x1f914', name: 'THINKING FACE' },
      { char: '🤕', code: '0x1f915', name: 'FACE WITH HEAD-BANDAGE' },
      { char: '🤖', code: '0x1f916', name: 'ROBOT FACE' },
      { char: '🤗', code: '0x1f917', name: 'HUGGING FACE' },
      { char: '🤘', code: '0x1f918', name: 'SIGN OF THE HORNS' },
      { char: '🤙', code: '0x1f919', name: 'CALL ME HAND' },
      { char: '🤚', code: '0x1f91a', name: 'RAISED BACK OF HAND' },
      { char: '🤝', code: '0x1f91d', name: 'HANDSHAKE' },
      { char: '🤞', code: '0x1f91e', name: 'HAND WITH INDEX AND MIDDLE FINGERS CROSSED' },
      { char: '🤟', code: '0x1f91f', name: 'I LOVE YOU HAND SIGN' },
      { char: '🤠', code: '0x1f920', name: 'FACE WITH COWBOY HAT' },
      { char: '🤡', code: '0x1f921', name: 'CLOWN FACE' },
      { char: '🤢', code: '0x1f922', name: 'NAUSEATED FACE' },
      { char: '🤤', code: '0x1f924', name: 'DROOLING FACE' },
      { char: '🤥', code: '0x1f925', name: 'LYING FACE' },
      { char: '🤦', code: '0x1f926', name: 'FACE PALM' },
      { char: '🤧', code: '0x1f927', name: 'SNEEZING FACE' },
      { char: '🤨', code: '0x1f928', name: 'FACE WITH ONE EYEBROW RAISED' },
      { char: '🤩', code: '0x1f929', name: 'GRINNING FACE WITH STAR EYES' },
      { char: '🤪', code: '0x1f92a', name: 'GRINNING FACE WITH ONE LARGE AND ONE SMALL EYE' },
      { char: '🤫', code: '0x1f92b', name: 'FACE WITH FINGER COVERING CLOSED LIPS' },
      { char: '🤬', code: '0x1f92c', name: 'SERIOUS FACE WITH SYMBOLS COVERING MOUTH' },
      { char: '🤭', code: '0x1f92d', name: 'SMILING FACE WITH SMILING EYES AND HAND COVERING MOUTH' },
      { char: '🤮', code: '0x1f92e', name: 'FACE WITH OPEN MOUTH VOMITING' },
      { char: '🤯', code: '0x1f92f', name: 'SHOCKED FACE WITH EXPLODING HEAD' },
      { char: '🥰', code: '0x1f970', name: 'SMILING FACE WITH SMILING EYES AND THREE HEARTS' },
      { char: '🥱', code: '0x1f971', name: 'YAWNING FACE' },
      { char: '🥲', code: '0x1f972', name: 'SMILING FACE WITH TEAR' },
      { char: '🥳', code: '0x1f973', name: 'FACE WITH PARTY HORN AND PARTY HAT' },
      { char: '🥴', code: '0x1f974', name: 'FACE WITH UNEVEN EYES AND WAVY MOUTH' },
      { char: '🥵', code: '0x1f975', name: 'OVERHEATED FACE' },
      { char: '🥶', code: '0x1f976', name: 'FREEZING FACE' },
      { char: '🥸', code: '0x1f978', name: 'DISGUISED FACE' },
      { char: '🥹', code: '0x1f979', name: 'FACE HOLDING BACK TEARS' },
      { char: '🥺', code: '0x1f97a', name: 'FACE WITH PLEADING EYES' },
      { char: '🦁', code: '0x1f981', name: 'LION FACE' },
      { char: '🦄', code: '0x1f984', name: 'UNICORN FACE' },
      { char: '🦊', code: '0x1f98a', name: 'FOX FACE' },
      { char: '🦒', code: '0x1f992', name: 'GIRAFFE FACE' },
      { char: '🦓', code: '0x1f993', name: 'ZEBRA FACE' },
      { char: '🧐', code: '0x1f9d0', name: 'FACE WITH MONOCLE' },
      { char: '🧡', code: '0x1f9e1', name: 'ORANGE HEART' },
    ],
    isCustom: true,
  },
  {
    id: 'emo_animals',
    label: '🐶 Animals & Nature',
    group: 'Emojis',
    icon: '🐶',
    symbols: [
      { char: '🐭', code: '0x1f42d', name: 'MOUSE FACE' },
      { char: '🐮', code: '0x1f42e', name: 'COW FACE' },
      { char: '🐯', code: '0x1f42f', name: 'TIGER FACE' },
      { char: '🐰', code: '0x1f430', name: 'RABBIT FACE' },
      { char: '🐱', code: '0x1f431', name: 'CAT FACE' },
      { char: '🐲', code: '0x1f432', name: 'DRAGON FACE' },
      { char: '🐴', code: '0x1f434', name: 'HORSE FACE' },
      { char: '🐵', code: '0x1f435', name: 'MONKEY FACE' },
      { char: '🐶', code: '0x1f436', name: 'DOG FACE' },
      { char: '🐷', code: '0x1f437', name: 'PIG FACE' },
      { char: '🐸', code: '0x1f438', name: 'FROG FACE' },
      { char: '🐹', code: '0x1f439', name: 'HAMSTER FACE' },
      { char: '🐺', code: '0x1f43a', name: 'WOLF FACE' },
      { char: '🐻', code: '0x1f43b', name: 'BEAR FACE' },
      { char: '🐼', code: '0x1f43c', name: 'PANDA FACE' },
      { char: '🦁', code: '0x1f981', name: 'LION FACE' },
      { char: '🦄', code: '0x1f984', name: 'UNICORN FACE' },
      { char: '🦊', code: '0x1f98a', name: 'FOX FACE' },
      { char: '🦒', code: '0x1f992', name: 'GIRAFFE FACE' },
      { char: '🦓', code: '0x1f993', name: 'ZEBRA FACE' },
      { char: '🌲', code: '0x1f332', name: 'EVERGREEN TREE' },
      { char: '🌳', code: '0x1f333', name: 'DECIDUOUS TREE' },
      { char: '🌴', code: '0x1f334', name: 'PALM TREE' },
      { char: '🌻', code: '0x1f33b', name: 'SUNFLOWER' },
    ],
    isCustom: true,
  },
  {
    id: 'emo_food',
    label: '🍔 Food & Drink',
    group: 'Emojis',
    icon: '🍔',
    symbols: [
      { char: '🍥', code: '0x1f365', name: 'FISH CAKE WITH SWIRL DESIGN' },
      { char: '🍮', code: '0x1f36e', name: 'CUSTARD' },
      { char: '🍲', code: '0x1f372', name: 'POT OF FOOD' },
      { char: '🍵', code: '0x1f375', name: 'TEACUP WITHOUT HANDLE' },
      { char: '🍹', code: '0x1f379', name: 'TROPICAL DRINK' },
      { char: '🌲', code: '0x1f332', name: 'EVERGREEN TREE' },
      { char: '🌳', code: '0x1f333', name: 'DECIDUOUS TREE' },
      { char: '🌴', code: '0x1f334', name: 'PALM TREE' },
      { char: '🌻', code: '0x1f33b', name: 'SUNFLOWER' },
    ],
    isCustom: true,
  },
  {
    id: 'emo_travel',
    label: '🚗 Travel & Places',
    group: 'Emojis',
    icon: '🚗',
    symbols: [
      { char: '🚧', code: '0x1f6a7', name: 'CONSTRUCTION SIGN' },
      { char: '🚩', code: '0x1f6a9', name: 'TRIANGULAR FLAG ON POST' },
      { char: '🚫', code: '0x1f6ab', name: 'NO ENTRY SIGN' },
      { char: '🚬', code: '0x1f6ac', name: 'SMOKING SYMBOL' },
      { char: '🚭', code: '0x1f6ad', name: 'NO SMOKING SYMBOL' },
      { char: '🚮', code: '0x1f6ae', name: 'PUT LITTER IN ITS PLACE SYMBOL' },
      { char: '🚯', code: '0x1f6af', name: 'DO NOT LITTER SYMBOL' },
      { char: '🚰', code: '0x1f6b0', name: 'POTABLE WATER SYMBOL' },
      { char: '🚱', code: '0x1f6b1', name: 'NON-POTABLE WATER SYMBOL' },
      { char: '🚹', code: '0x1f6b9', name: 'MENS SYMBOL' },
      { char: '🚺', code: '0x1f6ba', name: 'WOMENS SYMBOL' },
      { char: '🚼', code: '0x1f6bc', name: 'BABY SYMBOL' },
      { char: '🛂', code: '0x1f6c2', name: 'PASSPORT CONTROL' },
      { char: '🛇', code: '0x1f6c7', name: 'PROHIBITED SIGN' },
      { char: '🛉', code: '0x1f6c9', name: 'BOYS SYMBOL' },
      { char: '🛊', code: '0x1f6ca', name: 'GIRLS SYMBOL' },
      { char: '🛑', code: '0x1f6d1', name: 'OCTAGONAL SIGN' },
    ],
    isCustom: true,
  },
  {
    id: 'emo_activities',
    label: '⚽ Activities',
    group: 'Emojis',
    icon: '⚽',
    symbols: [
      { char: '\u2018', code: '0x2018', name: 'LEFT SINGLE QUOTATION MARK' },
      { char: '\u2019', code: '0x2019', name: 'RIGHT SINGLE QUOTATION MARK' },
      { char: '\u201c', code: '0x201c', name: 'LEFT DOUBLE QUOTATION MARK' },
      { char: '\u201d', code: '0x201d', name: 'RIGHT DOUBLE QUOTATION MARK' },
      { char: '\u203c', code: '0x203c', name: 'DOUBLE EXCLAMATION MARK' },
      { char: '\u2047', code: '0x2047', name: 'DOUBLE QUESTION MARK' },
      { char: '\u2049', code: '0x2049', name: 'EXCLAMATION QUESTION MARK' },
      { char: '\u20ac', code: '0x20ac', name: 'EURO SIGN' },
      { char: '\u20b9', code: '0x20b9', name: 'INDIAN RUPEE SIGN' },
      { char: '\u20ba', code: '0x20ba', name: 'TURKISH LIRA SIGN' },
      { char: '\u20bd', code: '0x20bd', name: 'RUBLE SIGN' },
      { char: '\u20bf', code: '0x20bf', name: 'BITCOIN SIGN' },
      { char: '\u2122', code: '0x2122', name: 'TRADE MARK SIGN' },
      { char: '\u2126', code: '0x2126', name: 'OHM SIGN' },
      { char: '\u2212', code: '0x2212', name: 'MINUS SIGN' },
      { char: '\u2300', code: '0x2300', name: 'DIAMETER SIGN' },
      { char: '\u2318', code: '0x2318', name: 'PLACE OF INTEREST SIGN' },
      { char: '\u23fb', code: '0x23fb', name: 'POWER SYMBOL' },
      { char: '\u23fc', code: '0x23fc', name: 'POWER ON-OFF SYMBOL' },
      { char: '\u23fd', code: '0x23fd', name: 'POWER ON SYMBOL' },
      { char: '\u2400', code: '0x2400', name: 'SYMBOL FOR NULL' },
      { char: '\u2401', code: '0x2401', name: 'SYMBOL FOR START OF HEADING' },
      { char: '\u240d', code: '0x240d', name: 'SYMBOL FOR CARRIAGE RETURN' },
      { char: '\u2421', code: '0x2421', name: 'SYMBOL FOR DELETE' },
      { char: '\u24b6', code: '0x24b6', name: 'CIRCLED LATIN CAPITAL LETTER A' },
      { char: '\u24b7', code: '0x24b7', name: 'CIRCLED LATIN CAPITAL LETTER B' },
    ],
    isCustom: true,
  },
];
